on:
  push:
    branches: [main]
env:
    first: gopi
    last: krishna
    # FirSt: another-gopi
    NUMBER: 90
jobs:
  first:
    runs-on: ubuntu-latest
    env:
      first: kondaji
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v6.1.0
      - name: echo hello world
        run: echo "hello world" && ls -ltra
      - name: git status
        run: git status
      - name: update packages
        run: sudo apt update 
      - name: bye
        run: echo "byeeeeeeeeeeeee"
      - name: test env
        run: echo "${{env.first}} $last $FIRST $NUMBER"
  second:
    needs: ['first']
    runs-on: ubuntu-latest
    steps:
      - name: second
        run: echo "hello world from second job, first job is completed"
      - name: test env for second
        run: echo "${{env.first}} $last $FIRST $NUMBER ${{GITHUB_ACTION}}"
